### ISSUE TITLE
CSS 专栏 （2022-05-18）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/Learning-notes#33]
## 有趣的css 特性

css 可以转英文大小写

```css
p.uppercase {
  text-transform: uppercase;
}

p.lowercase {
  text-transform: lowercase;
}

p.capitalize {
  text-transform: capitalize;
}
```
