### ISSUE TITLE
docker系列 2022-10-16

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/Learning-notes#35]
新建一个yml 文件

```yml
version: '3.5'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=developer*#
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

postgres:
  image: postgres:10.14
  environment:
    - POSTGRES_USER=developer
    - POSTGRES_PASSWORD=developer
    - POSTGRES_DB=dev
  ports:
    - "5432:5432"
  volumes:
    - ./postgres/data:/var/lib/postgresql/data

mongodb:
  image: mongo:4.4
  environment:
    - MONGO_INITDB_ROOT_USERNAME=developer
    - MONGO_INITDB_ROOT_PASSWORD=developer*#
  ports:
    - "27017:27017"
  volumes:
    - ./mongo/data:/data/db

redis:
  images: redis:6.0.8
  ports:
    - "6379:6379"
  environment:
    - REDIS_REPLICATION_MODE=master
  volumes:
  - ./reids/data:/data

```
